### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 1Sh0t** [Aaronidk/Dorito-bot-discord.js#20]
═[Discord-Economy Database Loaded -V1.2.2]═[Support server: https://discord.gg/eBFKDbx]=
[MUSIC_LOADCMD] Loaded play
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOTDIR: not a directory, scandir './commands/utils.js/'
    at readdirSync (fs.js:955:3)
    at H:\Рабочий стол\Dorito-bot-discord.js-master\handlers\command.js:10:26
    at Array.forEach (<anonymous>)
    at module.exports (H:\Рабочий стол\Dorito-bot-discord.js-master\handlers\command.js:9:32)
    at H:\Рабочий стол\Dorito-bot-discord.js-master\index.js:16:37
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (H:\Рабочий стол\Dorito-bot-discord.js-master\index.js:15:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4052,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: './commands/utils.js/'
}

**Comment by Aaronidk** [comment]
Im currently working on a fix for many bugs.
