### ISSUE TITLE
Starting error

### ISSUE THREAD

**Issue by that1gayteen** [Aaronidk/Dorito-bot-discord.js#25]
**Describe the bug**
Start the bot to get a good ol' error.

**To Reproduce**
Simply Start the BAT

**Expected behavior**

**Screenshots**
https://prnt.sc/udatej

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
(node:1372) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (D:\Downloads\doritobot\doritobot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133:26)
    at Client.login (D:\Downloads\doritobot\doritobot\node_modules\discord.js\src\client\Client.js:222:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1372) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (D:\Downloads\doritobot\doritobot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133:26)
    at Client.login (D:\Downloads\doritobot\doritobot\node_modules\discord.js\src\client\Client.js:222:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by that1gayteen** [comment]
im dumb, i forgot to setup the config
